steps:
  npm-configure:
    params:
      registry-url: https://registry.yarnpkg.com
  npm-configure-for-publish:
    params:
      registry-url: https://registry.npmjs.org
  node-unit-tests:
    description: lwr build all project
    run:
      command: yarn workspaces foreach -v run lwr:build
notifications:
    email:
        address: laf@salesforce.com