name: merge

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18.18.2

jobs:
  build:
    name: Build
    runs-on: salesforce-experience-platform-emu-Ubuntu

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Dependencies & Build
        run: yarn install --frozen-lockfile

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}
